
title: Blog of Akira Taguchi
email: akirahattivatti@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a hacker's blog. The author is Akira Taguchi. The posts are meant to act as troubleshooting help for anyone coming across this blog via keywords.
baseurl: ""
url: "https://akirataguchi.github.io"
twitter_username: akiratviit
github_username:  akirataguchi115

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

minima:
  skin: auto
